[build]
builder = "NIXPACKS"
# 改用更明確的打包命令
buildCommand = "mvn clean package spring-boot:repackage -DskipTests"

[deploy]
# 改為明確指定 WAR 檔案位置
startCommand = "java -Dspring.profiles.active=prod -jar target/Coffeesouffle-0.0.1-SNAPSHOT.war"
healthcheckPath = "/"
healthcheckTimeout = 300

[service]
port = "8082"
