[build]
builder = "maven"
command = "mvn clean package -DskipTests"

[deploy]
startCommand = "java $JAVA_OPTS -jar target/Coffeesouffle-0.0.1-SNAPSHOT.war"
restartPolicyType = "ON_FAILURE"

[[ports]]
port = "8082"