[build]
builder = "nixpacks"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/Coffeesouffle-0.0.1-SNAPSHOT.war"
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
# 指定 Java 版本
jdk_version = "17"