[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[deploy]
# 修改為明確的 war 檔案路徑和名稱
startCommand = "java -jar /app/target/Coffeesouffle-0.0.1-SNAPSHOT.war --server.port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300

[service]
port = "8082"