[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dspring.profiles.active=prod -jar target/Coffeesouffle-0.0.1-SNAPSHOT.war"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[ports]]
port = "8082"